import type { LayerState } from '../shared/objectEvents.ts';
import { BoardObject } from './boardCanvas/boardObject.ts';
import { BoardLayer } from './boardCanvas/boardLayer.ts';
import { getRequiredElement } from './dom.ts';
const storedObjects: Map<number, BoardObject> = new Map();
const storedLayers: Map<number, BoardLayer> = new Map();
const storedLayerStates: Map<number, LayerState> = new Map();
const rightBar = getRequiredElement('rightBar', HTMLElement);
const layerBox = getRequiredElement('layerLayerObj', HTMLElement);
const layerTab = getRequiredElement('layerTab', HTMLElement);
const tokenTab = getRequiredElement('tokenTab', HTMLElement);
const rollTab = getRequiredElement('rollTab', HTMLElement);
const characterTab = getRequiredElement('characterTab', HTMLElement);
const hideRight = getRequiredElement('hideRightBar', HTMLButtonElement);
const chatBox = getRequiredElement('chatBox', HTMLElement);
const layerTop = getRequiredElement('layerTop', HTMLElement);
const layerMid = getRequiredElement('layerMid', HTMLElement);
const currLayerText = getRequiredElement('currLayerText', HTMLElement);
const layerBottom = getRequiredElement('layerBottom', HTMLElement);
const layerRenameInput = getRequiredElement('rename', HTMLInputElement);
const layerXInput = getRequiredElement('xChange', HTMLInputElement);
const layerYInput = getRequiredElement('yChange', HTMLInputElement);
const deleteButton = getRequiredElement('deleteLayerButton', HTMLElement);
const upButton = getRequiredElement('layerUpButton', HTMLElement);
const downButton = getRequiredElement('layerDownButton', HTMLElement);
const nameInput = getRequiredElement('tokenName', HTMLInputElement);
const nameLabel = getRequiredElement('tokenNameLabel', HTMLLabelElement);
const measureDegrees = getRequiredElement('measureDegrees', HTMLInputElement);
const viewButton = getRequiredElement('viewMenuButton', HTMLButtonElement);
const drawButton = getRequiredElement('drawMenuButton', HTMLButtonElement);
const modeMenu = getRequiredElement('modeMenuId', HTMLElement);
const can = getRequiredElement('board', HTMLCanvasElement);
const bottomBar = getRequiredElement('bottomBar', HTMLElement);
const colourContainer = getRequiredElement('colourContainer', HTMLElement);
const userContainer = getRequiredElement('userContainer', HTMLElement);
const showUserButton = getRequiredElement('showUser', HTMLButtonElement);
const showColourButton = getRequiredElement('showColour', HTMLButtonElement);
const showRollButton = getRequiredElement('showRoll', HTMLButtonElement);
const rollContainer = getRequiredElement('rollContainer', HTMLElement);
